USE DATABASE EMPLOYEE_DB;
USE SCHEMA PUBLIC;
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

--- sampling 1% of the data (  row(1) )
CREATE OR REPLACE VIEW ADDRESS_SAMPLE
AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
    SAMPLE ROW(1) SEED(27);



SELECT COUNT(*) FROM ADDRESS_SAMPLE;