CREATE DATABASE TASK_DB;


CREATE OR REPLACE TABLE CUSTOMER(

    CUSTOMER_ID INT AUTOINCREMENT START = 1 INCREMENT =1,
    FIRST_NAME STRING DEFAULT 'JENIFER',
    CREATE_DATE DATE
);


USE DATABASE TASK_DB;
USE SCHEMA PUBLIC;
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

SELECT *
FROM CUSTOMER;

----CREATING A STORE PROCEDUREE------
-------------------------------------
CREATE OR REPLACE PROCEDURE CUSTOMERS_INSERT_PROCEDURE (CREATE_DATE varchar)
RETURNS STRING NOT NULL
LANGUAGE JAVASCRIPT
AS 
    $$
    var sql_command = 'INSERT INTO CUSTOMER(CREATE_DATE) VALUES(:1);'
    snowflake.execute({
        sqlText: sql_command,
        binds: [CREATE_DATE]
    });
    return "successfully executed.";
    $$;
    
----TASK BASED ON THE PROCEDURE
CREATE OR REPLACE TASK CUSTOMER_TASK_PROCEDURE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS CALL CUSTOMERS_INSERT_PROCEDURE (CURRENT_TIMESTAMP);
--WHEN WE CREATE THE TASK WE MUST ACTIVETE THEM

ALTER TASK CUSTOMER_TASK_PROCEDURE RESUME;
ALTER TASK CUSTOMER_TASK_PROCEDURE SUSPEND;

SHOW TASKS;
SHOW PROCEDURES;


----see the historyu of the taask
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'CUSTOMER_TASK_PROCEDURE'
ORDER BY SCHEDULED_TIME DESC;


select * from customer;

