USE ROLE ACCOUNTADMIN; 
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CERTIFICATION_TEST_DB;
USE SCHEMA TEST;

LIST @S3_MOVIE;

--table to insert
SELECT * FROM ORDERS;

--unload data 
COPY INTO @S3_MOVIE/my_file
FROM ORDERS;