SHOW ROLES;

--set up marketin department
USE ROLE SYSADMIN;

CREATE DATABASE MARKETING;
CREATE SCHEMA SALES;
CREATE TABLE MARKETING.SALES.CAMPAING (ID INT, COST NUMERIC, SALES_AMOUNT NUMERIC);

--use USERADMIN or SECURITYADMIN to set up role
USE ROLE SECURITYADMIN;

--creeate role
CREATE OR REPLACE ROLE MARKETING_ADMIN;

CREATE USER INITIAL_USER
    PASSWORD = 'AbC13245#';


--assigne user
GRANT ROLE MARKETING_ADMIN TO USER INITIAL_USER;

--grant privileges
GRANT USAGE ON DATABASE MARKETING TO ROLE MARKETING_ADMIN;
GRANT USAGE ON SCHEMA MARKETING.SALES TO ROLE MARKETING_ADMIN;
GRANT SELECT ON TABLE MARKETING.SALES.CAMPAING TO ROLE MARKETING_ADMIN;


--assign warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MARKETING_ADMIN;

--GRANT CREATER TABLES
GRANT CREATE TABLE ON SCHEMA MARKETING.SALES TO ROLE MARKETING_ADMIN;

--SELECT on all tables
GRANT SELECT ON ALL TABLES IN SCHEMA MARKETING.SALES TO ROLE MARKETING_ADMIN;

--select on all future tables
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARKETING.SALES TO ROLE MARKETING_ADMIN;

--revoke usage on databse
REVOKE USAGE ON SCHEMA MARKETING.SALES FROM ROLE MARKETING_ADMIN;



--GRANT OWNERSHIOP
GRANT OWNERSHIP ON SCHEMA MARKETING.sales TO ROLE MARKETING_ADMIN;


--what are the privileges of the role
SHOW GRANTS TO ROLE MARKETING_ADMIN;

---to whom was the role assgined ?
SHOW GRANTS OF ROLE MARKETING_ADMIN;








