SELECT * 
FROM ORDERS_DB.PUBLIC.ORDERS;

--ADDING A NEW COLUMN DATE
ALTER TABLE ORDERS_DB.PUBLIC.ORDERS
ADD COLUMN DATE_order DATE;

--insert
INSERT INTO ORDERS_DB.PUBLIC.ORDERS (DATE_order)
select DATE(uniform(1,10,random());

--
SELECT * FROM ORDERS_DB.PUBLIC.ORDERS WHERE DATE_ORDER = '2024-07-20';
-- partition 
ALTER TABLE ORDERS_DB.PUBLIC.ORDERS CLUSTER BY ( DATE_ORDER );